version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - cluster.name=my-cluster
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-network  # Attach to custom Docker network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    volumes:
      - /Users/girishkumargupta/projects/elasticsearch/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic-network  # Attach to custom Docker network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - '5601:5601'
    networks:
      - elastic-network  # Attach to custom Docker network
    depends_on:
      - elasticsearch  # Ensure Elasticsearch is started before Kibana

networks:
  elastic-network:  # Define custom Docker network
    driver: bridge

volumes:
  esdata:
